import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  innercontainer: {
    width: width * 0.94,
    alignSelf: 'center',
    backgroundColor: COLORS.white,
  },
  main_Box: {
    width: width * 0.93,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: COLORS.gray10,
    marginBottom: height * 0.015,
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  imagebox: {
    width: width * 0.28,
    height: height * 0.12,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: width * 0.014,
    resizeMode: 'cover',
    borderRadius: 8,
  },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: height * 0.005,
  },
  bottomBox: {
    padding: width * 0.02,
    width: width * 0.63,
  },
  heading: {
    color: COLORS.black,
    fontSize: 12,
    width: width * 0.5,
    ...FONTS.fiveHundred,
    height: height * 0.046,
  },
  ratings: {
    color: COLORS.black,
    fontSize: 11,
    width: width * 0.22,
    ...FONTS.fiveHundred,
    marginBottom: -3,
  },
  ratebox: {
    width: width * 0.12,
    backgroundColor: COLORS.green,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: width * 0.001,
    justifyContent: 'center',
    borderRadius: 3,
    marginRight: width * 0.04,
  },
  rate: {
    color: COLORS.white,
    fontSize: 12,
    ...FONTS.fiveHundred,
    marginBottom: -3,
    marginRight: width * 0.005,
  },
  star: {
    width: width * 0.028,
    height: height * 0.014,
    resizeMode: 'stretch',
    tintColor: COLORS.white,
  },
  heartbox: {
    width: width * 0.07,
    height: height * 0.04,
    resizeMode: 'contain',
    position: 'absolute',
    right: 10,
    top: 5,
    alignItems: 'center',
  },
  heart: {
    width: width * 0.05,
    height: height * 0.04,
    resizeMode: 'contain',
  },
  subtitle: {
    color: COLORS.gray60,
    fontSize: 11,
    ...FONTS.fiveHundred,
    width: width * 0.6,
    height: height * 0.043,
  },
  mrp: {
    color: COLORS.gray60,
    fontSize: 11,
    ...FONTS.fiveHundred,
    marginBottom: -1,
  },
  mrpprice: {
    color: COLORS.gray60,
    fontSize: 11,
    ...FONTS.fiveHundred,
    textDecorationLine: 'line-through',
    width: width * 0.16,
  },
  off: {
    color: COLORS.lightgreen,
    fontSize: 11,
    ...FONTS.sixHundred,
    width: width * 0.2,
  },
  price: {
    color: COLORS.black,
    fontSize: 13,
    ...FONTS.sixHundred,
    width: width * 0.17,
  },

  addmorebox: {
    borderWidth: 1,
    borderColor: COLORS.red,
    alignSelf: 'center',
    marginBottom: height * 0.02,
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.93,
    justifyContent: 'center',
    height: height * 0.056,
    borderRadius: 6,
    backgroundColor: COLORS.white,
  },
  plus: {
    height: height * 0.03,
    width: width * 0.043,
    resizeMode: 'contain',
    marginHorizontal: width * 0.02,
  },
  addmore: {
    fontSize: 13,
    color: COLORS.red,
    fontFamily: FONTS.semiBold,
    marginBottom: -3,
  },
  price_bottom: {
    borderColor: COLORS.gray10,
    backgroundColor: COLORS.white,
    alignItems: 'center',
    paddingHorizontal: width * 0.05,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderWidth: 1,
    paddingVertical: height * 0.008,
    position: 'absolute',
    bottom: 2,
    width: width,
  },
  bottom_text1: {
    ...FONTS.sixHundred,
    color: COLORS.black,
    fontSize: 16,
    marginBottom: height * -0.01,
    textAlign: 'center',
  },
  bottom_text2: {
    color: COLORS.green,
    fontSize: 12,
    ...FONTS.fiveHundred,
  },
});
